bull/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bull.views import HomePageView

admin.site.site_header = 'Låfteweb-administrasjon'
admin.site.site_title = 'Låfteweb-admin'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^ovingsspeilet/', include('ovingsspeilet.urls', namespace='ovingsspeilet')),
    url(r'^$', HomePageView.as_view(), name='home')
]

members/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from members.models import Member, Group

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', DetailView.as_view(model=Member), name='detail'),
    url(r'^$', ListView.as_view(model=Member), name='list'),
    url(r'^groups/$', ListView.as_view(model=Group), name='group-list'),
    url(r'^groups/(?P<pk>\d+)/$', DetailView.as_view(model=Group), name='group-detail'),
]

ovingsspeilet/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from ovingsspeilet import views

urlpatterns = [
    url(r'^calendar', views.calendar, name='calendar'),
    url(r'^$', login_required(TemplateView.as_view(template_name="ovingsspeilet/rehearsal.html")), name='rehearsal'),
]

members/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class MemberManager(BaseUserManager):
    def create_user(self, username, password=None, **kwargs):
        if not username:
            raise ValueError('Members must have a valid username')

        member = self.model(
            username=username
        )

        member.set_password(password)
        member.save()

        return member

    def create_superuser(self, username, password, **kwargs):
        member = self.create_user(username, password, **kwargs)

        member.is_admin = True
        member.save()

        return member


class Member(AbstractBaseUser):
    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = 'medlem'
        verbose_name_plural = 'medlemmer'

    username = models.CharField(max_length=50, unique=True, verbose_name='brukernavn')

    first_name = models.CharField(max_length=50, blank=True, verbose_name='fornavn')
    last_name = models.CharField(max_length=50, blank=True, verbose_name='etternavn')

    email = models.EmailField(blank=True, verbose_name='e-post')
    phone_number = models.CharField(max_length=16, blank=True, verbose_name='telefonnummer')
    birth_date = models.DateField(blank=True, null=True, verbose_name='fødselsdato')

    is_admin = models.BooleanField(default=False, verbose_name='er admin')

    USERNAME_FIELD = 'username'

    objects = MemberManager()

    def __str__(self):
        return self.get_short_name()

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_short_name(self):
        return self.username

    def is_staff(self):
        return self.is_admin

    def is_active(self):
        return True

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True


class Group(models.Model):
    class Meta:
        verbose_name = 'gruppe'
        verbose_name_plural = 'grupper'

    name = models.CharField(unique=True, max_length=50, verbose_name='navn')
    users = models.ManyToManyField(Member, related_name='groups')
    is_admin = models.BooleanField(default=False, verbose_name='er admin')

    def __str__(self):
        return self.name


class GroupMembership(models.Model):
    member = models.ForeignKey(Member)
    group = models.ForeignKey(Group)


class GroupMembershipPeriod(models.Model):
    membership = models.ForeignKey(GroupMembership)

ovingsspeilet/models.py
from django.contrib import admin
from django.db import models
from bull.config import settings


class Event(models.Model):
    title = models.CharField(max_length=40, verbose_name='tittel')
    description = models.TextField(max_length=10000, blank=True, verbose_name='beskrivelse')
    created = models.DateTimeField(auto_now_add=True)
    date_start = models.DateTimeField(verbose_name='starttidspunkt')
    date_end = models.DateTimeField(verbose_name='sluttidspunkt')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, verbose_name='opprettet av')
    weekly = models.BooleanField(default=False, verbose_name='ukentlig', help_text='Repeter ukentlig.')
    admin_event = models.BooleanField(default=False, verbose_name='adminaktivitet',
                                      help_text='Kan kun endres av en admin.')

    def __unicode__(self):
        if self.title:
            return self.creator + " - " + self.title
        else:
            return self.creator + " - " + self.snippet[:40]

    def short(self):
        if self.description:
            return "<i>%s</i> - %s" % (self.title, self.description)
        else:
            return self.title

    short.allow_tags = True

    class Meta:
        verbose_name = 'aktivitet'
        verbose_name_plural = 'aktiviteter'


class EventAdmin(admin.ModelAdmin):
    list_display = ["title", "date_start", "description", "creator"]
    list_filter = ["creator"]


admin.site.register(Event, EventAdmin)

bull/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):

    template_name = 'home.html'

members/views.py
from django.shortcuts import render

# Create your views here.

ovingsspeilet/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.utils import timezone
from ovingsspeilet.models import Event


@login_required
def calendar(request):
    event_objects = Event.objects.all()
    events = []
    for event in event_objects:
        events.append({
            'id': event.id,
            'title': event.title,
            'start': timezone.localtime(event.date_start),
            'end': timezone.localtime(event.date_end)
        })
    return JsonResponse(events, safe=False)

templates/base.html
<!DOCTYPE html>
<html lang="no">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Låfteweb</title>

    <!-- Bootstrap -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    <!--<link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    {% block extra_head %}{% endblock %}
</head>
<body>
{% block body %}
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-laafte navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Låfteweb</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'members:detail' user.pk %}">Logget inn som {{ user.get_full_name }}</a></li>
                    {% else %}
                        <li><a>Logg inn</a></li>
                    {% endif %}
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    {% url 'home' as url %}
                    <li {% if url == request.path %}class="active"{% endif %}><a href="{{ url }}">Oversikt</a></li>
                    {% url 'members:list' as url %}
                    <li {% if url == request.path %}class="active"{% endif %}><a href="{{ url }}">Medlemmer</a></li>
                    {% url 'members:group-list' as url %}
                    <li {% if url == request.path %}class="active"{% endif %}><a href="{{ url }}">Grupper</a></li>
                    {% if user.is_authenticated %}
                        {% url 'ovingsspeilet:rehearsal' as url %}
                        <li {% if url == request.path %}class="active"{% endif %}><a href="{{ url }}">Øvingsspeilet</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-sm-9 col-md-10 col-sm-offset-3 col-md-offset-2 main">
                {% block content %}
                <h1>Musikerlåfte</h1>
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/static/js/bootstrap.min.js"></script>
{% block extra_scripts %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="page-header">Låfteweb - oversikt</h1>
{% endblock %}

templates/members/group_detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ object.name }}</h1>
    <p>Er en gruppe</p>
    <h3>Medlemmer:</h3>
    <ul>
    {% for member in group.users.all %}
        <li><a href="{% url 'members:detail' member.id %}">{{ member.get_full_name }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

templates/members/group_list.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="page-header">Grupper</h1>
    <table class="table">
    <thead>
    <tr>
        <th>Navn</th>
    </tr>
    </thead>
        <tbody>
        {% for group in object_list %}
            <tr><td><a href="{% url 'members:group-detail' group.id %}">{{ group.name }}</a></td></tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

templates/members/member_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object.get_full_name }}</h1>
    <p>{{ object.get_short_name }}</p>
    <ul>
        <li>{{ object.email }}</li>
        <li>{{ object.phone_number }}</li>
    </ul>
    <h3>Grupper:</h3>
    <ul>
        {% for group in object.groups.all %}
            <li><a href="{% url 'members:group-detail' group.id %}">{{ group.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/members/member_list.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="page-header">Medlemmer</h1>
    <table class="table">
    <thead>
    <tr>
        <th>Navn</th>
        <th>E-post</th>
        <th>Telefon</th>
        <th>Grupper</th>
    </tr>
    </thead>
    <tbody>
    {% for member in object_list %}
        <tr>
            <td><a href="{% url 'members:detail' member.pk %}">{{ member.get_full_name }}</a></td>
            <td>{{ member.email }}</td>
            <td>{{ member.phone_number }}</td>
            <td>
                {% for group in member.groups.all %}
                    <a href="{% url 'members:group-detail' group.id %}">
                        {{ group.name }}
                    </a>
                    {% if not forloop.last %}|{% endif %}
                {% endfor %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

templates/ovingsspeilet/rehearsal.html
{% extends 'base.html' %}

{% block extra_head %}
    <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.3.1/fullcalendar.min.css" rel="stylesheet">
{% endblock %}

{% block extra_scripts %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.3.1/fullcalendar.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.3.1/lang/nb.js"></script>
    <script type='text/javascript'>
        $(document).ready(function () {
            $('#calendar').fullCalendar({
                // put your options and callbacks here
                timezone: 'Europe/Oslo',
                defaultView: 'agendaWeek',
                allDaySlot: false,
                weekNumbers: true,
                editable: true,
                selectable: true,
                businessHours: {
                    start: '08:00',
                    end: '18:00',
                    dow: [1, 2, 3, 4, 5, 6, 0] // days of week. an array of zero-based day of week integers (0=Sunday)
                },
                events: '{% url 'ovingsspeilet:calendar' %}'
            })

        });
    </script>
{% endblock %}

{% block content %}
    <h1 class="page-header">Øvingsspeilet</h1>
    <div id="calendar"></div>
{% endblock %}